### ISSUE TITLE
list of launch files to get SLAM working in gazebo

### ISSUE THREAD

**Issue by enricobellocchio** [pvandervelde/zinger_nav#1]
Can i ask wich launch file do you use to get SLAM navigation working in gazebo with your URDF and your controller? (similar to the test you performed in the article https://www.petrikvandervelde.nl/posts/Swerve-drive-ros2-nav) thank you very much for sharing your work!

**Comment by pvandervelde** [comment]
I've updated the readme with some basic information and the command lines. Note that you will need the ignition package running so that the controllers are up and running and the robot description has been published.

Would you be willing to have a look at the PR and try to use the commands in the readme? Let me know if anything is missing. Feel free to comment on the PR.

**Comment by pvandervelde** [comment]
The readme has been improved in #2 so it should be more obvious now how to use this package. Closing this ticket for now. If you are still experiencing issues please open a new issue.
